import skdim
import numpy as np
import pandas as pd
from sklearn.discriminant_analysis import StandardScaler
import time

data = pd.read_csv(
    "./Datasets/Synthetic PMU Data/ACTIVSg2000 - Far West.csv")
data.dropna(inplace=True)

features = data[['Bus ODESSA 2 0 V pu',
 'Bus ODESSA 2 0 V angle',
 'Bus ODESSA 2 0 Frequency',
 'Bus PRESIDIO 2 0 V pu',
 'Bus PRESIDIO 2 0 V angle',
 'Bus PRESIDIO 2 0 Frequency',
 'Bus O DONNELL 1 0 V pu',
 'Bus O DONNELL 1 0 V angle',
 'Bus O DONNELL 1 0 Frequency',
 'Bus O DONNELL 1 1 V pu',
 'Bus O DONNELL 1 1 V angle',
 'Bus O DONNELL 1 1 Frequency',
 'Bus BIG SPRING 5 0 V pu',
 'Bus BIG SPRING 5 0 V angle',
 'Bus BIG SPRING 5 0 Frequency',
 'Bus BIG SPRING 5 1 V pu',
 'Bus BIG SPRING 5 1 V angle',
 'Bus BIG SPRING 5 1 Frequency',
 'Bus VAN HORN 0 V pu',
 'Bus VAN HORN 0 V angle',
 'Bus VAN HORN 0 Frequency',
 'Bus IRAAN 2 0 V pu',
 'Bus IRAAN 2 0 V angle',
 'Bus IRAAN 2 0 Frequency',
 'Bus IRAAN 2 1 V pu',
 'Bus IRAAN 2 1 V angle',
 'Bus IRAAN 2 1 Frequency',
 'Bus PRESIDIO 1 0 V pu',
 'Bus PRESIDIO 1 0 V angle',
 'Bus PRESIDIO 1 0 Frequency',
 'Bus PRESIDIO 1 1 V pu',
 'Bus PRESIDIO 1 1 V angle',
 'Bus PRESIDIO 1 1 Frequency',
 'Bus SANDERSON 0 V pu',
 'Bus SANDERSON 0 V angle',
 'Bus SANDERSON 0 Frequency',
 'Bus MONAHANS 2 0 V pu',
 'Bus MONAHANS 2 0 V angle',
 'Bus MONAHANS 2 0 Frequency',
 'Bus GRANDFALLS 0 V pu',
 'Bus GRANDFALLS 0 V angle',
 'Bus GRANDFALLS 0 Frequency',
 'Bus MARFA 0 V pu',
 'Bus MARFA 0 V angle',
 'Bus MARFA 0 Frequency',
 'Bus GARDEN CITY 0 V pu',
 'Bus GARDEN CITY 0 V angle',
 'Bus GARDEN CITY 0 Frequency',
 'Bus ODESSA 4 0 V pu',
 'Bus ODESSA 4 0 V angle',
 'Bus ODESSA 4 0 Frequency',
 'Bus NOTREES 0 V pu',
 'Bus NOTREES 0 V angle',
 'Bus NOTREES 0 Frequency',
 'Bus MIDLAND 4 0 V pu',
 'Bus MIDLAND 4 0 V angle',
 'Bus MIDLAND 4 0 Frequency',
 'Bus BIG SPRING 1 0 V pu',
 'Bus BIG SPRING 1 0 V angle',
 'Bus BIG SPRING 1 0 Frequency',
 'Bus BIG SPRING 1 1 V pu',
 'Bus BIG SPRING 1 1 V angle',
 'Bus BIG SPRING 1 1 Frequency',
 'Bus O DONNELL 2 0 V pu',
 'Bus O DONNELL 2 0 V angle',
 'Bus O DONNELL 2 0 Frequency',
 'Bus O DONNELL 2 1 V pu',
 'Bus O DONNELL 2 1 V angle',
 'Bus O DONNELL 2 1 Frequency',
 'Bus ODESSA 6 0 V pu',
 'Bus ODESSA 6 0 V angle',
 'Bus ODESSA 6 0 Frequency',
 'Bus BIG SPRINGS 0 V pu',
 'Bus BIG SPRINGS 0 V angle',
 'Bus BIG SPRINGS 0 Frequency',
 'Bus BIG SPRINGS 1 V pu',
 'Bus BIG SPRINGS 1 V angle',
 'Bus BIG SPRINGS 1 Frequency',
 'Bus MIDLAND 2 0 V pu',
 'Bus MIDLAND 2 0 V angle',
 'Bus MIDLAND 2 0 Frequency',
 'Bus COAHOMA 0 V pu',
 'Bus COAHOMA 0 V angle',
 'Bus COAHOMA 0 Frequency',
 'Bus MIDLAND 3 0 V pu',
 'Bus MIDLAND 3 0 V angle',
 'Bus MIDLAND 3 0 Frequency',
 'Bus ALPINE 0 V pu',
 'Bus ALPINE 0 V angle',
 'Bus ALPINE 0 Frequency',
 'Bus FORT DAVIS 0 V pu',
 'Bus FORT DAVIS 0 V angle',
 'Bus FORT DAVIS 0 Frequency',
 'Bus MCCAMEY 1 0 V pu',
 'Bus MCCAMEY 1 0 V angle',
 'Bus MCCAMEY 1 0 Frequency',
 'Bus MCCAMEY 1 1 V pu',
 'Bus MCCAMEY 1 1 V angle',
 'Bus MCCAMEY 1 1 Frequency',
 'Bus BIG SPRING 4 0 V pu',
 'Bus BIG SPRING 4 0 V angle',
 'Bus BIG SPRING 4 0 Frequency',
 'Bus BIG SPRING 4 1 V pu',
 'Bus BIG SPRING 4 1 V angle',
 'Bus BIG SPRING 4 1 Frequency',
 'Bus CRANE 0 V pu',
 'Bus CRANE 0 V angle',
 'Bus CRANE 0 Frequency',
 'Bus ODESSA 5 0 V pu',
 'Bus ODESSA 5 0 V angle',
 'Bus ODESSA 5 0 Frequency',
 'Bus FORT STOCKTON 1 0 V pu',
 'Bus FORT STOCKTON 1 0 V angle',
 'Bus FORT STOCKTON 1 0 Frequency',
 'Bus FORT STOCKTON 1 1 V pu',
 'Bus FORT STOCKTON 1 1 V angle',
 'Bus FORT STOCKTON 1 1 Frequency',
 'Bus ANDREWS 0 V pu',
 'Bus ANDREWS 0 V angle',
 'Bus ANDREWS 0 Frequency',
 'Bus FORSAN 0 V pu',
 'Bus FORSAN 0 V angle',
 'Bus FORSAN 0 Frequency',
 'Bus FORSAN 1 V pu',
 'Bus FORSAN 1 V angle',
 'Bus FORSAN 1 Frequency',
 'Bus FORSAN 2 V pu',
 'Bus FORSAN 2 V angle',
 'Bus FORSAN 2 Frequency',
 'Bus BIG LAKE 0 V pu',
 'Bus BIG LAKE 0 V angle',
 'Bus BIG LAKE 0 Frequency',
 'Bus MIDLAND 5 0 V pu',
 'Bus MIDLAND 5 0 V angle',
 'Bus MIDLAND 5 0 Frequency',
 'Bus OZONA 0 V pu',
 'Bus OZONA 0 V angle',
 'Bus OZONA 0 Frequency',
 'Bus MONAHANS 1 0 V pu',
 'Bus MONAHANS 1 0 V angle',
 'Bus MONAHANS 1 0 Frequency',
 'Bus MONAHANS 1 1 V pu',
 'Bus MONAHANS 1 1 V angle',
 'Bus MONAHANS 1 1 Frequency',
 'Bus MONAHANS 1 2 V pu',
 'Bus MONAHANS 1 2 V angle',
 'Bus MONAHANS 1 2 Frequency',
 'Bus MONAHANS 1 3 V pu',
 'Bus MONAHANS 1 3 V angle',
 'Bus MONAHANS 1 3 Frequency',
 'Bus MONAHANS 1 4 V pu',
 'Bus MONAHANS 1 4 V angle',
 'Bus MONAHANS 1 4 Frequency',
 'Bus MONAHANS 1 5 V pu',
 'Bus MONAHANS 1 5 V angle',
 'Bus MONAHANS 1 5 Frequency',
 'Bus MONAHANS 1 6 V pu',
 'Bus MONAHANS 1 6 V angle',
 'Bus MONAHANS 1 6 Frequency',
 'Bus STANTON 0 V pu',
 'Bus STANTON 0 V angle',
 'Bus STANTON 0 Frequency',
 'Bus ODONNELL 0 V pu',
 'Bus ODONNELL 0 V angle',
 'Bus ODONNELL 0 Frequency',
 'Bus LENORAH 0 V pu',
 'Bus LENORAH 0 V angle',
 'Bus LENORAH 0 Frequency',
 'Bus LENORAH 1 V pu',
 'Bus LENORAH 1 V angle',
 'Bus LENORAH 1 Frequency',
 'Bus IRAAN 3 0 V pu',
 'Bus IRAAN 3 0 V angle',
 'Bus IRAAN 3 0 Frequency',
 'Bus IRAAN 3 1 V pu',
 'Bus IRAAN 3 1 V angle',
 'Bus IRAAN 3 1 Frequency',
 'Bus IRAAN 3 2 V pu',
 'Bus IRAAN 3 2 V angle',
 'Bus IRAAN 3 2 Frequency',
 'Bus BIG SPRING 6 0 V pu',
 'Bus BIG SPRING 6 0 V angle',
 'Bus BIG SPRING 6 0 Frequency',
 'Bus BIG SPRING 6 1 V pu',
 'Bus BIG SPRING 6 1 V angle',
 'Bus BIG SPRING 6 1 Frequency',
 'Bus BIG SPRING 6 2 V pu',
 'Bus BIG SPRING 6 2 V angle',
 'Bus BIG SPRING 6 2 Frequency',
 'Bus ODESSA 3 0 V pu',
 'Bus ODESSA 3 0 V angle',
 'Bus ODESSA 3 0 Frequency',
 'Bus BIG SPRING 3 0 V pu',
 'Bus BIG SPRING 3 0 V angle',
 'Bus BIG SPRING 3 0 Frequency',
 'Bus BIG SPRING 3 1 V pu',
 'Bus BIG SPRING 3 1 V angle',
 'Bus BIG SPRING 3 1 Frequency',
 'Bus BIG SPRING 7 0 V pu',
 'Bus BIG SPRING 7 0 V angle',
 'Bus BIG SPRING 7 0 Frequency',
 'Bus MIDLAND 1 0 V pu',
 'Bus MIDLAND 1 0 V angle',
 'Bus MIDLAND 1 0 Frequency',
 'Bus IRAAN 1 0 V pu',
 'Bus IRAAN 1 0 V angle',
 'Bus IRAAN 1 0 Frequency',
 'Bus IRAAN 1 1 V pu',
 'Bus IRAAN 1 1 V angle',
 'Bus IRAAN 1 1 Frequency',
 'Bus ODESSA 1 0 V pu',
 'Bus ODESSA 1 0 V angle',
 'Bus ODESSA 1 0 Frequency',
 'Bus ODESSA 1 1 V pu',
 'Bus ODESSA 1 1 V angle',
 'Bus ODESSA 1 1 Frequency',
 'Bus ODESSA 1 2 V pu',
 'Bus ODESSA 1 2 V angle',
 'Bus ODESSA 1 2 Frequency',
 'Bus ODESSA 1 3 V pu',
 'Bus ODESSA 1 3 V angle',
 'Bus ODESSA 1 3 Frequency',
 'Bus ODESSA 1 4 V pu',
 'Bus ODESSA 1 4 V angle',
 'Bus ODESSA 1 4 Frequency',
 'Bus ODESSA 1 5 V pu',
 'Bus ODESSA 1 5 V angle',
 'Bus ODESSA 1 5 Frequency',
 'Bus ODESSA 1 6 V pu',
 'Bus ODESSA 1 6 V angle',
 'Bus ODESSA 1 6 Frequency',
 'Bus ODESSA 1 7 V pu',
 'Bus ODESSA 1 7 V angle',
 'Bus ODESSA 1 7 Frequency',
 'Bus ODESSA 1 8 V pu',
 'Bus ODESSA 1 8 V angle',
 'Bus ODESSA 1 8 Frequency',
 'Bus ODESSA 1 9 V pu',
 'Bus ODESSA 1 9 V angle',
 'Bus ODESSA 1 9 Frequency',
 'Bus ODESSA 1 10 V pu',
 'Bus ODESSA 1 10 V angle',
 'Bus ODESSA 1 10 Frequency',
 'Bus FORT STOCKTON 2 0 V pu',
 'Bus FORT STOCKTON 2 0 V angle',
 'Bus FORT STOCKTON 2 0 Frequency',
 'Bus FORT STOCKTON 3 0 V pu',
 'Bus FORT STOCKTON 3 0 V angle',
 'Bus FORT STOCKTON 3 0 Frequency',
 'Bus BIG SPRING 2 0 V pu',
 'Bus BIG SPRING 2 0 V angle',
 'Bus BIG SPRING 2 0 Frequency',
 'Bus KERMIT 0 V pu',
 'Bus KERMIT 0 V angle',
 'Bus KERMIT 0 Frequency',
 'Bus PECOS 0 V pu',
 'Bus PECOS 0 V angle',
 'Bus PECOS 0 Frequency',
 'Bus SHEFFIELD 0 V pu',
 'Bus SHEFFIELD 0 V angle',
 'Bus SHEFFIELD 0 Frequency',
 'Bus MCCAMEY 2 0 V pu',
 'Bus MCCAMEY 2 0 V angle',
 'Bus MCCAMEY 2 0 Frequency',
 'Bus LAMESA 0 V pu',
 'Bus LAMESA 0 V angle',
 'Bus LAMESA 0 Frequency',
 'Bus GOLDSMITH 0 V pu',
 'Bus GOLDSMITH 0 V angle',
 'Bus GOLDSMITH 0 Frequency',
 'Bus RALLS 2 0 V pu',
 'Bus RALLS 2 0 V angle',
 'Bus RALLS 2 0 Frequency']].astype(np.float32)

startTime = time.time()
# Scale the data
scaler = StandardScaler()
scaledFeatures = scaler.fit_transform(features)
scaleTime = time.time()
print(f"The time taken for Scaling is {scaleTime - startTime}")


#estimate global intrinsic dimension
danco = skdim.id.DANCo().fit(scaledFeatures)
#estimate local intrinsic dimension (dimension in k-nearest-neighborhoods around each point):
lpca = skdim.id.lPCA().fit_pw(scaledFeatures,
                              n_neighbors = 100,
                              n_jobs = 1)
                            
totalTime = time.time()
print(f"The time taken for Scaling is {totalTime - startTime}")
#get estimated intrinsic dimension
print(danco.dimension_, np.mean(lpca.dimension_pw_)) 


# 9 dimensions estimated